@startuml
'https://plantuml.com/sequence-diagram

autonumber
Main -> Application: Application started
Application -> StartMenu: Prompt user to log-in
StartMenu -> TextUI: displayMessage("Enter username:")
TextUI -> StartMenu: username = getInput()
StartMenu -> TextUI: If username is not found: "Create new user, or try again?"
TextUI -> StartMenu:
StartMenu -> TextUI: displayMessage("Enter password:")
TextUI -> StartMenu: password = getInput()

StartMenu -> StartMenu: Create new user

StartMenu -> Application: return user to currentUser

@enduml